
import React from "react";
import { Link } from "react-router-dom";

function Disclaimer() {

  return (

    <main className="disclaimer-page">


      {/* HEADER */}

      <section className="disclaimer-header">

        <div>

          <div className="section-label">
            IMPORTANT INFORMATION
          </div>

          <h1>
            Understanding your
            <span>NutriLens results.</span>
          </h1>

          <p>
            Please read this information before using
            NutriLens screening results or nutrition
            recommendations.
          </p>

        </div>


        <div className="disclaimer-header-icon">
          !
        </div>

      </section>



      {/* MAIN WARNING */}

      <section className="main-disclaimer-card">

        <div className="main-warning-icon">
          !
        </div>

        <div>

          <span>
            IMPORTANT
          </span>

          <h2>
            NutriLens is a screening tool,
            not a medical diagnostic system.
          </h2>

          <p>
            The results generated by NutriLens are intended
            for screening, educational, and general awareness
            purposes only.
          </p>

        </div>

      </section>



      {/* INFORMATION GRID */}

      <section className="disclaimer-grid">


        {/* WHAT IT CAN DO */}

        <article className="info-card">

          <div className="info-card-number">
            01
          </div>

          <div className="info-card-icon">
            ✓
          </div>

          <h3>
            What NutriLens can do
          </h3>

          <p>
            NutriLens can analyze an uploaded image using
            an AI-based computer vision model and identify
            visual patterns that may be associated with
            certain nutritional concerns.
          </p>

        </article>



        {/* WHAT IT CANNOT DO */}

        <article className="info-card">

          <div className="info-card-number">
            02
          </div>

          <div className="info-card-icon">
            ×
          </div>

          <h3>
            What NutriLens cannot do
          </h3>

          <p>
            NutriLens cannot confirm a micronutrient
            deficiency, diagnose a disease, prescribe
            medication, or replace a healthcare professional.
          </p>

        </article>



        {/* VISUAL LIMITATION */}

        <article className="info-card">

          <div className="info-card-number">
            03
          </div>

          <div className="info-card-icon">
            ◇
          </div>

          <h3>
            Visual results have limitations
          </h3>

          <p>
            Similar visual characteristics can occur due to
            many different factors. An image alone cannot
            reliably determine the underlying cause.
          </p>

        </article>



        {/* PROFESSIONAL TESTING */}

        <article className="info-card">

          <div className="info-card-number">
            04
          </div>

          <div className="info-card-icon">
            +
          </div>

          <h3>
            Professional testing matters
          </h3>

          <p>
            If you have persistent symptoms or concerns
            about your nutritional status, consult a
            qualified healthcare professional and consider
            appropriate laboratory testing.
          </p>

        </article>


      </section>



      {/* IMPORTANT NOTICE */}

      <section className="testing-notice">

        <div className="testing-notice-icon">
          i
        </div>

        <div>

          <span>
            FOR YOUR SAFETY
          </span>

          <h2>
            Do not make health decisions
            based only on an AI screening result.
          </h2>

          <p>
            Use NutriLens as an awareness and educational
            tool. A healthcare professional can evaluate
            your symptoms, medical history, diet, and
            appropriate test results to determine whether
            further investigation is needed.
          </p>

        </div>

      </section>



      {/* RESULT INTERPRETATION */}

      <section className="interpretation-section">

        <div className="interpretation-heading">

          <span>
            HOW TO INTERPRET RESULTS
          </span>

          <h2>
            Think of the result as a starting point,
            not a conclusion.
          </h2>

        </div>


        <div className="interpretation-steps">

          <div className="interpretation-step">

            <strong>
              01
            </strong>

            <div>

              <h3>
                Review
              </h3>

              <p>
                Understand the possible nutritional concern
                identified by the screening model.
              </p>

            </div>

          </div>


          <div className="interpretation-step">

            <strong>
              02
            </strong>

            <div>

              <h3>
                Learn
              </h3>

              <p>
                Explore the general nutrition recommendations
                provided by NutriLens.
              </p>

            </div>

          </div>


          <div className="interpretation-step">

            <strong>
              03
            </strong>

            <div>

              <h3>
                Verify
              </h3>

              <p>
                Seek professional advice and appropriate
                testing when necessary.
              </p>

            </div>

          </div>

        </div>

      </section>



      {/* FINAL NOTICE */}

      <section className="final-disclaimer">

        <div>

          <strong>
            NutriLens provides screening and awareness,
            not medical diagnosis.
          </strong>

          <p>
            By using the application, you acknowledge that
            its results are informational and should not be
            used as a substitute for professional healthcare.
          </p>

        </div>


        <Link
          to="/"
          className="primary-button"
        >
          Return Home →
        </Link>

      </section>


    </main>

  );

}

export default Disclaimer;